### ISSUE TITLE
Support .NET Core

### ISSUE THREAD

**Issue by CRC32EX** [extremecodetv/SocksSharp#4]
Please support .NET Core

**Comment by extremecodetv** [comment]
At the beginning of the development metstandard2 was not released, this library uses many platform features like SslStream or Begin/End async pattern from .NET Framework. 

This all requires detailed study with a new standard. I'll do it in my spare time, thank you for the suggestion

**Comment by CRC32EX** [comment]
`.NET Standard 2.0` is supports `System.Web`.
in my environment, successfully finished compiling this project.  without changes.

`.NET Standard 1.6` or earlier  is compile faild.
because `System.Web` is not supported.

i think, just change NuGet build option.
add dependecies `.NET Standard 2.0.0`
code change is not needed.

sorry, i don't have NuGet experience.

**Comment by extremecodetv** [comment]
@CRC32EX Migration to netstandard2 completed, you can use library in netcore applications
